# Travis config to publish electron build for Mac, Windows and PC onto github releases 
os: osx
osx_image: xcode9.4
language: node_js
node_js: "12.13.0" # one of node js travis pre installed versions
sudo: required

before_install:
  - node --version
  # - npm i -g npm@6.1.0
  - npm --version

install:
  - npm install

cache:
  npm: true
  node: true

env:
  global:
    # from https://www.electron.build/configuration/publish#githuboptions
    # - EP_DRAFT=false
    # - EP_PRE_RELEASE=false
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - PUBLISH_FOR_PULL_REQUEST=true
    - USE_HARD_LINKS=false
    - YARN_GPG=no

script:
  - npm run build:mwl:publish:always;
  - ls ./dist;
  - find . | grep .dmg;
  - find . | grep .AppImage;
  - find . | grep .exe;

branches:
except:
  - # Do not build tags that we create when we upload to GitHub Releases
  - /^(?i:continuous)/